# 使用官方 Python 镜像
FROM python:3.11-slim

# 设置工作目录
WORKDIR /app

# 复制项目文件
COPY . .

# 安装系统依赖
RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev \
    default-libmysqlclient-dev \
    pkg-config \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip install  -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple --verbose



# 设置环境变量（可选）
ENV FLASK_ENV=production

# 暴露端口
EXPOSE 5000

# 运行 Flask 应用
CMD ["python", "run.py"]